/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemmanajemenkontak;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.mysql.cj.protocol.Resultset;
import com.mysql.cj.xdevapi.Statement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Advie Rifaldy
 */
public class KontakForm extends javax.swing.JFrame {

    /**
     * Creates new form KontakForm
     */
    public Connection con;
    public PreparedStatement pst;
    public KontakForm kf = this;

    public void Connect() throws ClassNotFoundException {
        try {
            // below two lines are used for connectivity.
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_kontak", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(AddKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public KontakForm() {
        initComponents();
        this.setLocation(440, 160);

        try {
            Connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddKategori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKontak = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        addKategoriBtn = new javax.swing.JButton();
        reloadKontak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 28)); // NOI18N
        jLabel2.setText("Sistem Informasi Kontak");
        jLabel2.setToolTipText("");

        tableKontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Email", "No Telepon", "Kategori "
            }
        ));
        jScrollPane1.setViewportView(tableKontak);
        if (tableKontak.getColumnModel().getColumnCount() > 0) {
            tableKontak.getColumnModel().getColumn(0).setPreferredWidth(24);
            tableKontak.getColumnModel().getColumn(0).setMaxWidth(24);
            tableKontak.getColumnModel().getColumn(1).setPreferredWidth(160);
            tableKontak.getColumnModel().getColumn(1).setMaxWidth(160);
            tableKontak.getColumnModel().getColumn(2).setPreferredWidth(320);
            tableKontak.getColumnModel().getColumn(2).setMaxWidth(320);
        }

        jButton1.setText("Tambah Kontak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addKategoriBtn.setText("Tambah Kategori");
        addKategoriBtn.setToolTipText("");
        addKategoriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKategoriBtnActionPerformed(evt);
            }
        });

        reloadKontak.setText("Reload 🔄️");
        reloadKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadKontakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addKategoriBtn)
                        .addGap(528, 528, 528)
                        .addComponent(reloadKontak)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addKategoriBtn)
                    .addComponent(jButton1)
                    .addComponent(reloadKontak))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddKontak add = new AddKontak();
        add.setVisible(true);
        add.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        add.setTitle("Tambah Kontak");
        add.setLocation(460, 280);
        add.fetchKategori();
        add.setPrev(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addKategoriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKategoriBtnActionPerformed
        // TODO add your handling code here:
        AddKategori add = new AddKategori();
        add.setVisible(true);
        add.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        add.setTitle("Tambah Kategori");
        add.setLocation(460, 280);
    }//GEN-LAST:event_addKategoriBtnActionPerformed

    private void reloadKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadKontakActionPerformed
        // TODO add your handling code here:
        fetchKontak();
    }//GEN-LAST:event_reloadKontakActionPerformed

    public void fetchKontak() {
        try {
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM kontak");
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();

            int columnsNumber = rsmd.getColumnCount();

            System.out.println("Kontak : Ok");
            DefaultTableModel df = (DefaultTableModel) tableKontak.getModel();

            df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 0; i < columnsNumber; i++) {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("nama"));
                    v2.add(rs.getString("alamat"));
                    v2.add(rs.getString("email"));
                    v2.add(rs.getString("no_telepon"));
                    v2.add(rs.getString("kategori_id"));
                }
                df.addRow(v2);
            }

            // Add the onclick event to the table
            tableKontak.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    int selectedRow = tableKontak.getSelectedRow();
                    if (selectedRow != -1) {
                        String id = (String) tableKontak.getValueAt(selectedRow, 0);
                        String nama = (String) tableKontak.getValueAt(selectedRow, 1);
                        String alamat = (String) tableKontak.getValueAt(selectedRow, 2);
                        String email = (String) tableKontak.getValueAt(selectedRow, 3);
                        String no_telepon = (String) tableKontak.getValueAt(selectedRow, 4);
                        String kategori_id = (String) tableKontak.getValueAt(selectedRow, 5);

                        UpdateKontak update = new UpdateKontak();
                        update.setVisible(true);
                        update.setLocation(460, 280);
                        update.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        update.setTitle("Update Data " + nama);
                        update.fetchKategori();
                        update.setId(id);
                        update.nama.setText(nama);
                        update.alamat.setText(alamat);
                        update.email.setText(email);
                        update.no_telepon.setText(no_telepon);
                        update.selectKategori.setSelectedItem(kategori_id);
                        update.setPrev(kf);
                    }
                }
            });
        } catch (SQLException ex) {
            Logger.getLogger(KontakForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void closeFrame() {
        this.dispose(); // Close the frame
    }

//    public void fetchKategori() {
//        try {
//            java.sql.Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery("SELECT * FROM kategori");
//            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
//
//            int columnsNumber = rsmd.getColumnCount();
//            
//            System.out.println("Kategori : Ok");
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(KontakForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontakForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontakForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addKategoriBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reloadKontak;
    private javax.swing.JTable tableKontak;
    // End of variables declaration//GEN-END:variables
}
